### ISSUE TITLE
ListAddressTransactions does not include data property

### ISSUE THREAD

**Issue by iiian** [JonathanCrossland/multichain#14]
`AddressTransactionResponse` does not include the property `data` (typeof `List<string>` I believe).

This is used by the call to `ListAddresTranscations`,`ListAddresTranscationsAsync`,`ListWalletTransactions`,`ListWalletTransactionsAsync`

**Comment by JonathanCrossland** [comment]
This has been added. Thanks for your comment. 
Finally, I am in a position to update this project.
