### ISSUE TITLE
SignRawTransactionAsync accept only one parameter txHex

### ISSUE THREAD

**Issue by zinouker** [JonathanCrossland/multichain#29]
i want to sign raw transaction by passing also the private key how to do this ?

**Comment by JonathanCrossland** [comment]
Its been a long time. I have been away but back to the project for another period of time.|
In the interested of others coming here with a similar question, see below.


In a typical use case, you would create a raw transaction using createrawtransaction, sign it using signrawtransaction, and then send it to the network using sendrawtransaction. However, note that signrawtransaction signs the transaction with the private keys of addresses in your wallet; it doesn't allow you to manually specify a private key.

If you need to sign a transaction with a specific private key, you might need to:

Import the private key into your wallet using importprivkey.
Use signrawtransaction to sign the transaction.
Optionally, remove the private key if you do not want to keep it in your wallet using dumpprivkey and removeaddress.
