### ISSUE TITLE
Unable to open connection using MultiChainConnection object

### ISSUE THREAD

**Issue by Tiyyob** [JonathanCrossland/multichain#33]
Good Day,

I am trying to work on a Hello world web application using LucidOcean.Multichain assembly using C# in Microsoft Visual Studio 2017. I am just trying to make a connection from the server to the server.

Following is my sample code taken from Multichain Developers website

MultiChainConnection connection = new MultiChainConnection()
                {
                    Hostname = "xxx.xxx.xx.79",
                    Port = 7349,
                    Username = "multichainrpc",
                    Password = "F4oMLnguUvNYyT6ZUjKQY7r7auGCYzgB8NncZDdZS8QE",
                    ChainName = "ChainName",
                    BurnAddress = "1XXXXXXWzyXXXXXXg2XXXXXXcTXXXXXXXqFAPD",
                    RootNodeAddress = "1WNtXcjb8L9c96JnQbwsQKFPBxgnm1AJK5zd5F"
                };

                
                MultiChainClient _Client = new MultiChainClient(connection);                
                JsonRpcResponse<string> response= _Client.Wallet.GetNewAddress();

When I run the daemon command, resulting information gives me two ports to work with, 
First port is 7349 given in the following lines

•	Other nodes can connect to this node using:
•	multichaind ChainName@169.254.88.79:7349

If I use 7349 as a port, code throws following exception

**The underlying connection was closed: The connection was closed unexpectedly**

Second port is 7348 taken from following lines

•	Listening for API requests on port 7348 (local only - see rpcallowip setting)

If use 7348 as a port, code throws following exception

**Unable to connect to the remote server, No connection could be made because the target machine actively refused it 169.254.88.79:7348**

Please advise what port I should use and what could be the problem prohibiting the connection?

**Comment by delphikit** [comment]
Is the hello world app running on the same or different server as the MultiChain server?

**Comment by Tiyyob** [comment]
Yes, it is running on the same server.

**Comment by delphikit** [comment]
Can you try to use 127.0.0.1 for the host IP? And for your case I think the RPC port should be 7348.

**Comment by Tiyyob** [comment]
Many thanks for your reply, the problem has been resolved by setting "rpcallowip" parameter in "multichain.conf" file and now I can connect with my blockchain.

If you know any existing documentation for "LucidOcean.Multichain" , please let me know. It will be a big help. :-)
