### ISSUE TITLE
Can I use this repo to recover some tokens?

### ISSUE THREAD

**Issue by zydjohnHotmail** [JonathanCrossland/multichain#37]
Hello:
I found this repo, and I have one specific job to do, I want to get some advice on how to procceed.
A few weeks ago, I sent some Ruff (Ruff Chain) tokens from one exchange via HECO network to another exchange, but the receiver supports only ERC20 network for Ruff tokens, and the sender supports only HECO network for sending Ruff tokens.  The receiver exchange recently release a new tool, which I can use to recover those tokens, but I have to pay 100USDT each time I use their tool.
Now, I have the API keys for both exchanges. And I can login to my accounts on both exchanges.
I want to know is it possible in my case to use multi-chain commands to recover the Ruff tokens, I mean simply to switch the tokens from HECO network to ERC20 network.
If possible, then what commands I have to use, and what kind of privilege I should have to run those commands.
Finally, if this way will NOT work, then is it possible that I setup a multi-chain wallet, just like MetaMask, create one address for 2 different networks, like: ERC20 and TRC20, then send some real tokens from one exchange to this multi-chain address, then run some multi-chain commands, switch the network, and send the received tokens to another exchange.
I have good experience with .NET/C# on windows, some experience with JavaScript (Node.js), but not an expert. I am using Windows 10 PRO, Visual Studio 2022 (version 17.4.1) and Node.js (ver 19.0.1)
Please advise,
Thanks,

**Comment by JonathanCrossland** [comment]
Not without some coding contributions.

**Comment by zydjohnHotmail** [comment]
Hello:
I think you can ignore this issue. This could be time consuming.  But can you answer my new issue?
Can I use this repo to create a multi-chain wallet, which can use wallet address to receive tokens from different networks and send the received tokens to other address via different network.
For example, I want to create a multi-chain wallet with addresses can support ERC20, BEP20 and HECO network.
Then I want to be able to receive some USDT from HECO network, afterwards, I want to be able to send those USDT to another address in ERC20/BEP20 networks.
If I can do this, please provide some general idea on how to proceed.
I can have quite some time for coding now in C#.
Thanks,

**Comment by JonathanCrossland** [comment]
This library is purely a wrapper for RPC calls to multichain nodes, which was forked from bitcoin. Not all the protocols and rpc calls are implemented. It would take some work to make that happen.

**Comment by zydjohnHotmail** [comment]
Hello:
I am reading the RPC documents, I see it has a lot of commands.  But I think I need only 2 or most 3 commands: Check Account balance on the wallet address, which connect multiple networks.  Then find the gas fees for the target address with different network, finally send the tokens to the target address with the gas fee payment.
I think if I can use the CLI command line, the current version for Windows is 2.3.1, then I can do all the jobs I need, I don't need anything else.  As I can save private key or other stuff in my local database, which is rather safe.
I think I need only 4 networks to use RPC CLI: ERC20, BEP20, TRC20 and HECO, other networks are useless now in my case.
But I also have to read your code in order to make it works later on.
Please advise, if using your code to call multichain RPC can do the above 2 or 3 things.
By the way, is there any playground or test net or something I can play around with RPC CLI? So, after I am familiar with those command, I can use your code to call them.
Please advise,
Thanks,

**Comment by JonathanCrossland** [comment]
Docs are here.
https://www.multichain.com/developers/json-rpc-api/

**Comment by zydjohnHotmail** [comment]
Thanks:
I will spend some time to read it, but can you advise where can I play those RPC command on some test net? I don't want to play with main net, which could lose some money if not familiar with those commands, as the parameters are always complicated, esp., those address.
Thanks,
